[pytest]
markers =
    login_guest: tests for login from main page
    login: tests for user login and registration
    add_to_basket: tests for adding products to basket
    need_review: tests for final review